// Generated by scripts/gallery-api.cjs --write; review ownership and fixtures with API changes.
// prettier-ignore
export const componentApi = [
  {
    "name": "AccessKeyInstructions",
    "source": "features/sync/s3-setup-guide.view.tsx",
    "family": "S04",
    "exported": false,
    "axes": {}
  },
  {
    "name": "Accordion",
    "source": "components/primitives/accordion.tsx",
    "family": "B14",
    "exported": true,
    "axes": {
      "orientation": [
        "horizontal",
        "vertical"
      ]
    }
  },
  {
    "name": "AccordionContent",
    "source": "components/primitives/accordion.tsx",
    "family": "B14",
    "exported": true,
    "axes": {}
  },
  {
    "name": "AccordionItem",
    "source": "components/primitives/accordion.tsx",
    "family": "B14",
    "exported": true,
    "axes": {}
  },
  {
    "name": "AccordionTrigger",
    "source": "components/primitives/accordion.tsx",
    "family": "B14",
    "exported": true,
    "axes": {}
  },
  {
    "name": "ActionFeedback",
    "source": "components/feedback/action-feedback.view.tsx",
    "family": "P26",
    "exported": true,
    "axes": {}
  },
  {
    "name": "Alert",
    "source": "components/primitives/alert.tsx",
    "family": "B10",
    "exported": true,
    "axes": {
      "variant": [
        "default",
        "destructive"
      ]
    }
  },
  {
    "name": "AlertAction",
    "source": "components/primitives/alert.tsx",
    "family": "B10",
    "exported": true,
    "axes": {}
  },
  {
    "name": "AlertDescription",
    "source": "components/primitives/alert.tsx",
    "family": "B10",
    "exported": true,
    "axes": {}
  },
  {
    "name": "AlertDialog",
    "source": "components/primitives/alert-dialog.tsx",
    "family": "B17",
    "exported": true,
    "axes": {}
  },
  {
    "name": "AlertDialogAction",
    "source": "components/primitives/alert-dialog.tsx",
    "family": "B17",
    "exported": true,
    "axes": {
      "variant": [
        "default",
        "destructive",
        "ghost",
        "link",
        "outline",
        "secondary"
      ],
      "size": [
        "default",
        "icon",
        "icon-lg",
        "icon-sm",
        "icon-xs",
        "lg",
        "sm",
        "xs"
      ]
    }
  },
  {
    "name": "AlertDialogCancel",
    "source": "components/primitives/alert-dialog.tsx",
    "family": "B17",
    "exported": true,
    "axes": {
      "variant": [
        "default",
        "destructive",
        "ghost",
        "link",
        "outline",
        "secondary"
      ],
      "size": [
        "default",
        "icon",
        "icon-lg",
        "icon-sm",
        "icon-xs",
        "lg",
        "sm",
        "xs"
      ]
    }
  },
  {
    "name": "AlertDialogContent",
    "source": "components/primitives/alert-dialog.tsx",
    "family": "B17",
    "exported": true,
    "axes": {
      "size": [
        "default",
        "sm"
      ]
    }
  },
  {
    "name": "AlertDialogDescription",
    "source": "components/primitives/alert-dialog.tsx",
    "family": "B17",
    "exported": true,
    "axes": {}
  },
  {
    "name": "AlertDialogFooter",
    "source": "components/primitives/alert-dialog.tsx",
    "family": "B17",
    "exported": true,
    "axes": {}
  },
  {
    "name": "AlertDialogHeader",
    "source": "components/primitives/alert-dialog.tsx",
    "family": "B17",
    "exported": true,
    "axes": {}
  },
  {
    "name": "AlertDialogMedia",
    "source": "components/primitives/alert-dialog.tsx",
    "family": "B17",
    "exported": true,
    "axes": {}
  },
  {
    "name": "AlertDialogOverlay",
    "source": "components/primitives/alert-dialog.tsx",
    "family": "B17",
    "exported": true,
    "axes": {}
  },
  {
    "name": "AlertDialogPortal",
    "source": "components/primitives/alert-dialog.tsx",
    "family": "B17",
    "exported": true,
    "axes": {}
  },
  {
    "name": "AlertDialogTitle",
    "source": "components/primitives/alert-dialog.tsx",
    "family": "B17",
    "exported": true,
    "axes": {}
  },
  {
    "name": "AlertDialogTrigger",
    "source": "components/primitives/alert-dialog.tsx",
    "family": "B17",
    "exported": true,
    "axes": {}
  },
  {
    "name": "AlertTitle",
    "source": "components/primitives/alert.tsx",
    "family": "B10",
    "exported": true,
    "axes": {}
  },
  {
    "name": "AppNavigation",
    "source": "entrypoints/components/app-navigation.view.tsx",
    "family": "P28",
    "exported": true,
    "axes": {}
  },
  {
    "name": "Attachment",
    "source": "components/primitives/attachment.tsx",
    "family": "B26",
    "exported": true,
    "axes": {
      "size": [
        "default",
        "sm",
        "xs"
      ],
      "orientation": [
        "horizontal",
        "vertical"
      ]
    }
  },
  {
    "name": "AttachmentAction",
    "source": "components/primitives/attachment.tsx",
    "family": "B26",
    "exported": true,
    "axes": {
      "variant": [
        "default",
        "destructive",
        "ghost",
        "link",
        "outline",
        "secondary"
      ],
      "size": [
        "default",
        "icon",
        "icon-lg",
        "icon-sm",
        "icon-xs",
        "lg",
        "sm",
        "xs"
      ]
    }
  },
  {
    "name": "AttachmentActions",
    "source": "components/primitives/attachment.tsx",
    "family": "B26",
    "exported": true,
    "axes": {}
  },
  {
    "name": "AttachmentContent",
    "source": "components/primitives/attachment.tsx",
    "family": "B26",
    "exported": true,
    "axes": {}
  },
  {
    "name": "AttachmentDescription",
    "source": "components/primitives/attachment.tsx",
    "family": "B26",
    "exported": true,
    "axes": {}
  },
  {
    "name": "AttachmentGroup",
    "source": "components/primitives/attachment.tsx",
    "family": "B26",
    "exported": true,
    "axes": {}
  },
  {
    "name": "AttachmentMedia",
    "source": "components/primitives/attachment.tsx",
    "family": "B26",
    "exported": true,
    "axes": {
      "variant": [
        "icon",
        "image"
      ]
    }
  },
  {
    "name": "AttachmentTitle",
    "source": "components/primitives/attachment.tsx",
    "family": "B26",
    "exported": true,
    "axes": {}
  },
  {
    "name": "AttachmentTrigger",
    "source": "components/primitives/attachment.tsx",
    "family": "B26",
    "exported": true,
    "axes": {}
  },
  {
    "name": "Avatar",
    "source": "components/primitives/avatar.tsx",
    "family": "B38",
    "exported": true,
    "axes": {
      "size": [
        "default",
        "lg",
        "sm"
      ]
    }
  },
  {
    "name": "AvatarBadge",
    "source": "components/primitives/avatar.tsx",
    "family": "B38",
    "exported": true,
    "axes": {}
  },
  {
    "name": "AvatarFallback",
    "source": "components/primitives/avatar.tsx",
    "family": "B38",
    "exported": true,
    "axes": {}
  },
  {
    "name": "AvatarGroup",
    "source": "components/primitives/avatar.tsx",
    "family": "B38",
    "exported": true,
    "axes": {}
  },
  {
    "name": "AvatarGroupCount",
    "source": "components/primitives/avatar.tsx",
    "family": "B38",
    "exported": true,
    "axes": {}
  },
  {
    "name": "AvatarImage",
    "source": "components/primitives/avatar.tsx",
    "family": "B38",
    "exported": true,
    "axes": {}
  },
  {
    "name": "Badge",
    "source": "components/primitives/badge.tsx",
    "family": "B11",
    "exported": true,
    "axes": {
      "variant": [
        "default",
        "destructive",
        "ghost",
        "link",
        "outline",
        "secondary"
      ]
    }
  },
  {
    "name": "BrowserLoginsPanel",
    "source": "features/entries/browser-logins.view.tsx",
    "family": "S01",
    "exported": true,
    "axes": {
      "mode": [
        "detected",
        "matches"
      ]
    }
  },
  {
    "name": "Button",
    "source": "components/primitives/button.tsx",
    "family": "B01",
    "exported": true,
    "axes": {
      "variant": [
        "default",
        "destructive",
        "ghost",
        "link",
        "outline",
        "secondary"
      ],
      "size": [
        "default",
        "icon",
        "icon-lg",
        "icon-sm",
        "icon-xs",
        "lg",
        "sm",
        "xs"
      ]
    }
  },
  {
    "name": "ButtonGroup",
    "source": "components/primitives/button-group.tsx",
    "family": "B25",
    "exported": true,
    "axes": {
      "orientation": [
        "horizontal",
        "vertical"
      ]
    }
  },
  {
    "name": "ButtonGroupSeparator",
    "source": "components/primitives/button-group.tsx",
    "family": "B25",
    "exported": true,
    "axes": {
      "orientation": [
        "horizontal",
        "vertical"
      ]
    }
  },
  {
    "name": "ButtonGroupText",
    "source": "components/primitives/button-group.tsx",
    "family": "B25",
    "exported": true,
    "axes": {}
  },
  {
    "name": "Card",
    "source": "components/primitives/card.tsx",
    "family": "B23",
    "exported": true,
    "axes": {
      "size": [
        "default",
        "sm"
      ]
    }
  },
  {
    "name": "CardAction",
    "source": "components/primitives/card.tsx",
    "family": "B23",
    "exported": true,
    "axes": {}
  },
  {
    "name": "CardContent",
    "source": "components/primitives/card.tsx",
    "family": "B23",
    "exported": true,
    "axes": {}
  },
  {
    "name": "CardDescription",
    "source": "components/primitives/card.tsx",
    "family": "B23",
    "exported": true,
    "axes": {}
  },
  {
    "name": "CardFooter",
    "source": "components/primitives/card.tsx",
    "family": "B23",
    "exported": true,
    "axes": {}
  },
  {
    "name": "CardHeader",
    "source": "components/primitives/card.tsx",
    "family": "B23",
    "exported": true,
    "axes": {}
  },
  {
    "name": "CardTitle",
    "source": "components/primitives/card.tsx",
    "family": "B23",
    "exported": true,
    "axes": {}
  },
  {
    "name": "Checkbox",
    "source": "components/primitives/checkbox.tsx",
    "family": "B07",
    "exported": true,
    "axes": {}
  },
  {
    "name": "Combobox",
    "source": "components/primitives/combobox.tsx",
    "family": "B24",
    "exported": true,
    "axes": {}
  },
  {
    "name": "ComboboxChip",
    "source": "components/primitives/combobox.tsx",
    "family": "B24",
    "exported": true,
    "axes": {}
  },
  {
    "name": "ComboboxChips",
    "source": "components/primitives/combobox.tsx",
    "family": "B24",
    "exported": true,
    "axes": {}
  },
  {
    "name": "ComboboxChipsInput",
    "source": "components/primitives/combobox.tsx",
    "family": "B24",
    "exported": true,
    "axes": {}
  },
  {
    "name": "ComboboxClear",
    "source": "components/primitives/combobox.tsx",
    "family": "B24",
    "exported": false,
    "axes": {}
  },
  {
    "name": "ComboboxCollection",
    "source": "components/primitives/combobox.tsx",
    "family": "B24",
    "exported": true,
    "axes": {}
  },
  {
    "name": "ComboboxContent",
    "source": "components/primitives/combobox.tsx",
    "family": "B24",
    "exported": true,
    "axes": {
      "side": [
        "bottom",
        "inline-end",
        "inline-start",
        "left",
        "right",
        "top"
      ],
      "align": [
        "center",
        "end",
        "start"
      ]
    }
  },
  {
    "name": "ComboboxEmpty",
    "source": "components/primitives/combobox.tsx",
    "family": "B24",
    "exported": true,
    "axes": {}
  },
  {
    "name": "ComboboxGroup",
    "source": "components/primitives/combobox.tsx",
    "family": "B24",
    "exported": true,
    "axes": {}
  },
  {
    "name": "ComboboxInput",
    "source": "components/primitives/combobox.tsx",
    "family": "B24",
    "exported": true,
    "axes": {}
  },
  {
    "name": "ComboboxItem",
    "source": "components/primitives/combobox.tsx",
    "family": "B24",
    "exported": true,
    "axes": {}
  },
  {
    "name": "ComboboxLabel",
    "source": "components/primitives/combobox.tsx",
    "family": "B24",
    "exported": true,
    "axes": {}
  },
  {
    "name": "ComboboxList",
    "source": "components/primitives/combobox.tsx",
    "family": "B24",
    "exported": true,
    "axes": {}
  },
  {
    "name": "ComboboxSeparator",
    "source": "components/primitives/combobox.tsx",
    "family": "B24",
    "exported": true,
    "axes": {
      "orientation": [
        "horizontal",
        "vertical"
      ]
    }
  },
  {
    "name": "ComboboxTrigger",
    "source": "components/primitives/combobox.tsx",
    "family": "B24",
    "exported": true,
    "axes": {}
  },
  {
    "name": "ComboboxValue",
    "source": "components/primitives/combobox.tsx",
    "family": "B24",
    "exported": true,
    "axes": {}
  },
  {
    "name": "ComparisonRow",
    "source": "features/sync/sync-review.view.tsx",
    "family": "P22",
    "exported": true,
    "axes": {}
  },
  {
    "name": "CopyAction",
    "source": "components/feedback/action-feedback.view.tsx",
    "family": "P14",
    "exported": true,
    "axes": {}
  },
  {
    "name": "CredentialForm",
    "source": "features/sync/credential-form.view.tsx",
    "family": "F05",
    "exported": true,
    "axes": {
      "mode": [
        "connect-existing",
        "repair",
        "setup"
      ]
    }
  },
  {
    "name": "DestructiveConfirmation",
    "source": "components/feedback/destructive-confirmation.view.tsx",
    "family": "P25",
    "exported": true,
    "axes": {}
  },
  {
    "name": "DetailField",
    "source": "components/layout/sections.view.tsx",
    "family": "P12",
    "exported": true,
    "axes": {}
  },
  {
    "name": "DeviceManagementView",
    "source": "features/devices/device-management.view.tsx",
    "family": "S02",
    "exported": true,
    "axes": {}
  },
  {
    "name": "DeviceSettingsForm",
    "source": "features/devices/device-settings-form.view.tsx",
    "family": "F07",
    "exported": true,
    "axes": {}
  },
  {
    "name": "DeviceSummary",
    "source": "features/devices/devices.view.tsx",
    "family": "P23",
    "exported": true,
    "axes": {}
  },
  {
    "name": "Dialog",
    "source": "components/primitives/dialog.tsx",
    "family": "B19",
    "exported": true,
    "axes": {}
  },
  {
    "name": "DialogClose",
    "source": "components/primitives/dialog.tsx",
    "family": "B19",
    "exported": true,
    "axes": {}
  },
  {
    "name": "DialogContent",
    "source": "components/primitives/dialog.tsx",
    "family": "B19",
    "exported": true,
    "axes": {}
  },
  {
    "name": "DialogDescription",
    "source": "components/primitives/dialog.tsx",
    "family": "B19",
    "exported": true,
    "axes": {}
  },
  {
    "name": "DialogFooter",
    "source": "components/primitives/dialog.tsx",
    "family": "B19",
    "exported": true,
    "axes": {}
  },
  {
    "name": "DialogHeader",
    "source": "components/primitives/dialog.tsx",
    "family": "B19",
    "exported": true,
    "axes": {}
  },
  {
    "name": "DialogOverlay",
    "source": "components/primitives/dialog.tsx",
    "family": "B19",
    "exported": true,
    "axes": {}
  },
  {
    "name": "DialogPortal",
    "source": "components/primitives/dialog.tsx",
    "family": "B19",
    "exported": true,
    "axes": {}
  },
  {
    "name": "DialogTitle",
    "source": "components/primitives/dialog.tsx",
    "family": "B19",
    "exported": true,
    "axes": {}
  },
  {
    "name": "DialogTrigger",
    "source": "components/primitives/dialog.tsx",
    "family": "B19",
    "exported": true,
    "axes": {}
  },
  {
    "name": "DropdownMenu",
    "source": "components/primitives/dropdown-menu.tsx",
    "family": "B16",
    "exported": true,
    "axes": {
      "orientation": [
        "horizontal",
        "vertical"
      ]
    }
  },
  {
    "name": "DropdownMenuCheckboxItem",
    "source": "components/primitives/dropdown-menu.tsx",
    "family": "B16",
    "exported": true,
    "axes": {}
  },
  {
    "name": "DropdownMenuContent",
    "source": "components/primitives/dropdown-menu.tsx",
    "family": "B16",
    "exported": true,
    "axes": {
      "side": [
        "bottom",
        "inline-end",
        "inline-start",
        "left",
        "right",
        "top"
      ],
      "align": [
        "center",
        "end",
        "start"
      ]
    }
  },
  {
    "name": "DropdownMenuGroup",
    "source": "components/primitives/dropdown-menu.tsx",
    "family": "B16",
    "exported": true,
    "axes": {}
  },
  {
    "name": "DropdownMenuItem",
    "source": "components/primitives/dropdown-menu.tsx",
    "family": "B16",
    "exported": true,
    "axes": {
      "variant": [
        "default",
        "destructive"
      ]
    }
  },
  {
    "name": "DropdownMenuLabel",
    "source": "components/primitives/dropdown-menu.tsx",
    "family": "B16",
    "exported": true,
    "axes": {}
  },
  {
    "name": "DropdownMenuPortal",
    "source": "components/primitives/dropdown-menu.tsx",
    "family": "B16",
    "exported": true,
    "axes": {}
  },
  {
    "name": "DropdownMenuRadioGroup",
    "source": "components/primitives/dropdown-menu.tsx",
    "family": "B16",
    "exported": true,
    "axes": {}
  },
  {
    "name": "DropdownMenuRadioItem",
    "source": "components/primitives/dropdown-menu.tsx",
    "family": "B16",
    "exported": true,
    "axes": {}
  },
  {
    "name": "DropdownMenuSeparator",
    "source": "components/primitives/dropdown-menu.tsx",
    "family": "B16",
    "exported": true,
    "axes": {
      "orientation": [
        "horizontal",
        "vertical"
      ]
    }
  },
  {
    "name": "DropdownMenuShortcut",
    "source": "components/primitives/dropdown-menu.tsx",
    "family": "B16",
    "exported": true,
    "axes": {}
  },
  {
    "name": "DropdownMenuSub",
    "source": "components/primitives/dropdown-menu.tsx",
    "family": "B16",
    "exported": true,
    "axes": {
      "orientation": [
        "horizontal",
        "vertical"
      ]
    }
  },
  {
    "name": "DropdownMenuSubContent",
    "source": "components/primitives/dropdown-menu.tsx",
    "family": "B16",
    "exported": true,
    "axes": {
      "side": [
        "bottom",
        "inline-end",
        "inline-start",
        "left",
        "right",
        "top"
      ],
      "align": [
        "center",
        "end",
        "start"
      ]
    }
  },
  {
    "name": "DropdownMenuSubTrigger",
    "source": "components/primitives/dropdown-menu.tsx",
    "family": "B16",
    "exported": true,
    "axes": {}
  },
  {
    "name": "DropdownMenuTrigger",
    "source": "components/primitives/dropdown-menu.tsx",
    "family": "B16",
    "exported": true,
    "axes": {}
  },
  {
    "name": "Empty",
    "source": "components/primitives/empty.tsx",
    "family": "B21",
    "exported": true,
    "axes": {}
  },
  {
    "name": "EmptyContent",
    "source": "components/primitives/empty.tsx",
    "family": "B21",
    "exported": true,
    "axes": {}
  },
  {
    "name": "EmptyDescription",
    "source": "components/primitives/empty.tsx",
    "family": "B21",
    "exported": true,
    "axes": {}
  },
  {
    "name": "EmptyHeader",
    "source": "components/primitives/empty.tsx",
    "family": "B21",
    "exported": true,
    "axes": {}
  },
  {
    "name": "EmptyMedia",
    "source": "components/primitives/empty.tsx",
    "family": "B21",
    "exported": true,
    "axes": {
      "variant": [
        "default",
        "icon"
      ]
    }
  },
  {
    "name": "EmptyState",
    "source": "components/layout/sections.view.tsx",
    "family": "P15",
    "exported": true,
    "axes": {}
  },
  {
    "name": "EmptyTitle",
    "source": "components/primitives/empty.tsx",
    "family": "B21",
    "exported": true,
    "axes": {}
  },
  {
    "name": "EntryDetails",
    "source": "features/entries/entry-details.view.tsx",
    "family": "P12",
    "exported": true,
    "axes": {}
  },
  {
    "name": "EntryEditor",
    "source": "features/entries/entry-editor.view.tsx",
    "family": "F02",
    "exported": true,
    "axes": {
      "mode": [
        "add",
        "edit"
      ]
    }
  },
  {
    "name": "EntryForm",
    "source": "features/entries/entry-form.view.tsx",
    "family": "F02",
    "exported": true,
    "axes": {
      "mode": [
        "add",
        "edit"
      ]
    }
  },
  {
    "name": "EntryList",
    "source": "features/entries/entries.view.tsx",
    "family": "P11",
    "exported": true,
    "axes": {
      "presentation": [
        "default",
        "popup"
      ]
    }
  },
  {
    "name": "EntryRow",
    "source": "features/entries/entries.view.tsx",
    "family": "P11",
    "exported": true,
    "axes": {
      "presentation": [
        "default",
        "popup"
      ]
    }
  },
  {
    "name": "EntrySelection",
    "source": "features/entries/entries.view.tsx",
    "family": "P11",
    "exported": true,
    "axes": {
      "presentation": [
        "default",
        "popup"
      ]
    }
  },
  {
    "name": "EntryTable",
    "source": "features/entries/entry-table.view.tsx",
    "family": "P11",
    "exported": true,
    "axes": {}
  },
  {
    "name": "EntryWorkspace",
    "source": "features/entries/entry-workspace.view.tsx",
    "family": "S02",
    "exported": true,
    "axes": {}
  },
  {
    "name": "Field",
    "source": "components/primitives/field.tsx",
    "family": "B02",
    "exported": true,
    "axes": {
      "orientation": [
        "horizontal",
        "responsive",
        "vertical"
      ]
    }
  },
  {
    "name": "FieldContent",
    "source": "components/primitives/field.tsx",
    "family": "B02",
    "exported": true,
    "axes": {}
  },
  {
    "name": "FieldDescription",
    "source": "components/primitives/field.tsx",
    "family": "B02",
    "exported": true,
    "axes": {}
  },
  {
    "name": "FieldError",
    "source": "components/primitives/field.tsx",
    "family": "B02",
    "exported": true,
    "axes": {}
  },
  {
    "name": "FieldGroup",
    "source": "components/primitives/field.tsx",
    "family": "B02",
    "exported": true,
    "axes": {}
  },
  {
    "name": "FieldLabel",
    "source": "components/primitives/field.tsx",
    "family": "B02",
    "exported": true,
    "axes": {}
  },
  {
    "name": "FieldLegend",
    "source": "components/primitives/field.tsx",
    "family": "B02",
    "exported": true,
    "axes": {
      "variant": [
        "label",
        "legend"
      ]
    }
  },
  {
    "name": "FieldSeparator",
    "source": "components/primitives/field.tsx",
    "family": "B02",
    "exported": true,
    "axes": {}
  },
  {
    "name": "FieldSet",
    "source": "components/primitives/field.tsx",
    "family": "B02",
    "exported": true,
    "axes": {}
  },
  {
    "name": "FieldTitle",
    "source": "components/primitives/field.tsx",
    "family": "B02",
    "exported": true,
    "axes": {}
  },
  {
    "name": "FolderCount",
    "source": "features/folders/folder-tree.view.tsx",
    "family": "P31",
    "exported": false,
    "axes": {}
  },
  {
    "name": "FolderEditor",
    "source": "features/folders/folder-editor.view.tsx",
    "family": "P31",
    "exported": true,
    "axes": {
      "mode": [
        "add",
        "edit"
      ]
    }
  },
  {
    "name": "FolderManagementContent",
    "source": "features/folders/folder-management.view.tsx",
    "family": "S05",
    "exported": false,
    "axes": {}
  },
  {
    "name": "FolderManagementView",
    "source": "features/folders/folder-management.view.tsx",
    "family": "S05",
    "exported": true,
    "axes": {}
  },
  {
    "name": "FolderPicker",
    "source": "features/folders/folder-tree.view.tsx",
    "family": "P31",
    "exported": true,
    "axes": {}
  },
  {
    "name": "FolderTree",
    "source": "features/folders/folder-tree.view.tsx",
    "family": "P31",
    "exported": true,
    "axes": {}
  },
  {
    "name": "FormActions",
    "source": "components/forms/fields.view.tsx",
    "family": "F01",
    "exported": true,
    "axes": {}
  },
  {
    "name": "FormFrame",
    "source": "components/forms/form-frame.view.tsx",
    "family": "F01",
    "exported": true,
    "axes": {}
  },
  {
    "name": "FormPassword",
    "source": "components/forms/form-frame.view.tsx",
    "family": "P05",
    "exported": true,
    "axes": {}
  },
  {
    "name": "GeneratedValue",
    "source": "features/password-tools/generator.view.tsx",
    "family": "P20",
    "exported": true,
    "axes": {}
  },
  {
    "name": "GeneratorControls",
    "source": "features/password-tools/generator.view.tsx",
    "family": "P20",
    "exported": true,
    "axes": {}
  },
  {
    "name": "GuidancePanel",
    "source": "components/feedback/guidance-panel.view.tsx",
    "family": "P29",
    "exported": true,
    "axes": {
      "variant": [
        "info",
        "warning"
      ]
    }
  },
  {
    "name": "Input",
    "source": "components/primitives/input.tsx",
    "family": "B03",
    "exported": true,
    "axes": {}
  },
  {
    "name": "InputGroup",
    "source": "components/primitives/input-group.tsx",
    "family": "B04",
    "exported": true,
    "axes": {}
  },
  {
    "name": "InputGroupAddon",
    "source": "components/primitives/input-group.tsx",
    "family": "B04",
    "exported": true,
    "axes": {
      "align": [
        "block-end",
        "block-start",
        "inline-end",
        "inline-start"
      ]
    }
  },
  {
    "name": "InputGroupButton",
    "source": "components/primitives/input-group.tsx",
    "family": "B04",
    "exported": true,
    "axes": {
      "variant": [
        "default",
        "destructive",
        "ghost",
        "link",
        "outline",
        "secondary"
      ],
      "size": [
        "icon-sm",
        "icon-xs",
        "sm",
        "xs"
      ]
    }
  },
  {
    "name": "InputGroupInput",
    "source": "components/primitives/input-group.tsx",
    "family": "B04",
    "exported": true,
    "axes": {}
  },
  {
    "name": "InputGroupText",
    "source": "components/primitives/input-group.tsx",
    "family": "B04",
    "exported": true,
    "axes": {}
  },
  {
    "name": "InputGroupTextarea",
    "source": "components/primitives/input-group.tsx",
    "family": "B04",
    "exported": true,
    "axes": {}
  },
  {
    "name": "Item",
    "source": "components/primitives/item.tsx",
    "family": "B22",
    "exported": true,
    "axes": {
      "variant": [
        "default",
        "muted",
        "outline"
      ],
      "size": [
        "default",
        "sm",
        "xs"
      ]
    }
  },
  {
    "name": "ItemActions",
    "source": "components/primitives/item.tsx",
    "family": "B22",
    "exported": true,
    "axes": {}
  },
  {
    "name": "ItemContent",
    "source": "components/primitives/item.tsx",
    "family": "B22",
    "exported": true,
    "axes": {}
  },
  {
    "name": "ItemDescription",
    "source": "components/primitives/item.tsx",
    "family": "B22",
    "exported": true,
    "axes": {}
  },
  {
    "name": "ItemFooter",
    "source": "components/primitives/item.tsx",
    "family": "B22",
    "exported": true,
    "axes": {}
  },
  {
    "name": "ItemGroup",
    "source": "components/primitives/item.tsx",
    "family": "B22",
    "exported": true,
    "axes": {}
  },
  {
    "name": "ItemHeader",
    "source": "components/primitives/item.tsx",
    "family": "B22",
    "exported": true,
    "axes": {}
  },
  {
    "name": "ItemMedia",
    "source": "components/primitives/item.tsx",
    "family": "B22",
    "exported": true,
    "axes": {
      "variant": [
        "default",
        "icon",
        "image"
      ]
    }
  },
  {
    "name": "ItemSeparator",
    "source": "components/primitives/item.tsx",
    "family": "B22",
    "exported": true,
    "axes": {
      "orientation": [
        "horizontal",
        "vertical"
      ]
    }
  },
  {
    "name": "ItemTitle",
    "source": "components/primitives/item.tsx",
    "family": "B22",
    "exported": true,
    "axes": {}
  },
  {
    "name": "Kbd",
    "source": "components/primitives/kbd.tsx",
    "family": "B37",
    "exported": true,
    "axes": {}
  },
  {
    "name": "KbdGroup",
    "source": "components/primitives/kbd.tsx",
    "family": "B37",
    "exported": true,
    "axes": {}
  },
  {
    "name": "Label",
    "source": "components/primitives/label.tsx",
    "family": "B02",
    "exported": true,
    "axes": {}
  },
  {
    "name": "LocalRecoveryForm",
    "source": "features/recovery/local-recovery-form.view.tsx",
    "family": "F06",
    "exported": true,
    "axes": {}
  },
  {
    "name": "LockDurationField",
    "source": "components/forms/fields.view.tsx",
    "family": "P07",
    "exported": true,
    "axes": {}
  },
  {
    "name": "MoveFolderDialog",
    "source": "features/folders/move-folder-dialog.view.tsx",
    "family": "P31",
    "exported": true,
    "axes": {}
  },
  {
    "name": "NativeSelect",
    "source": "components/primitives/native-select.tsx",
    "family": "B06",
    "exported": true,
    "axes": {
      "size": [
        "default",
        "lg",
        "sm"
      ]
    }
  },
  {
    "name": "NativeSelectOptGroup",
    "source": "components/primitives/native-select.tsx",
    "family": "B06",
    "exported": true,
    "axes": {}
  },
  {
    "name": "NativeSelectOption",
    "source": "components/primitives/native-select.tsx",
    "family": "B06",
    "exported": true,
    "axes": {}
  },
  {
    "name": "OptionsView",
    "source": "entrypoints/options/options.view.tsx",
    "family": "S02",
    "exported": true,
    "axes": {}
  },
  {
    "name": "OrganizationManagementView",
    "source": "features/organization/organization-management.view.tsx",
    "family": "S05",
    "exported": true,
    "axes": {}
  },
  {
    "name": "Pagination",
    "source": "components/primitives/pagination.tsx",
    "family": "B30",
    "exported": true,
    "axes": {}
  },
  {
    "name": "PaginationContent",
    "source": "components/primitives/pagination.tsx",
    "family": "B30",
    "exported": true,
    "axes": {}
  },
  {
    "name": "PaginationEllipsis",
    "source": "components/primitives/pagination.tsx",
    "family": "B30",
    "exported": true,
    "axes": {}
  },
  {
    "name": "PaginationItem",
    "source": "components/primitives/pagination.tsx",
    "family": "B30",
    "exported": true,
    "axes": {}
  },
  {
    "name": "PaginationLink",
    "source": "components/primitives/pagination.tsx",
    "family": "B30",
    "exported": true,
    "axes": {
      "size": [
        "default",
        "icon",
        "icon-lg",
        "icon-sm",
        "icon-xs",
        "lg",
        "sm",
        "xs"
      ]
    }
  },
  {
    "name": "PaginationNext",
    "source": "components/primitives/pagination.tsx",
    "family": "B30",
    "exported": true,
    "axes": {
      "size": [
        "default",
        "icon",
        "icon-lg",
        "icon-sm",
        "icon-xs",
        "lg",
        "sm",
        "xs"
      ]
    }
  },
  {
    "name": "PaginationPrevious",
    "source": "components/primitives/pagination.tsx",
    "family": "B30",
    "exported": true,
    "axes": {
      "size": [
        "default",
        "icon",
        "icon-lg",
        "icon-sm",
        "icon-xs",
        "lg",
        "sm",
        "xs"
      ]
    }
  },
  {
    "name": "PasswordChangeForm",
    "source": "features/vault-access/access-forms.view.tsx",
    "family": "F04",
    "exported": true,
    "axes": {}
  },
  {
    "name": "PasswordCreationForm",
    "source": "features/vault-setup/password-creation-form.view.tsx",
    "family": "F03",
    "exported": true,
    "axes": {}
  },
  {
    "name": "PasswordField",
    "source": "components/forms/fields.view.tsx",
    "family": "P05",
    "exported": true,
    "axes": {}
  },
  {
    "name": "PasswordStrengthFeedback",
    "source": "components/forms/fields.view.tsx",
    "family": "P06",
    "exported": true,
    "axes": {}
  },
  {
    "name": "PasswordToolsPage",
    "source": "features/password-tools/password-tools-page.view.tsx",
    "family": "S02",
    "exported": true,
    "axes": {
      "presentation": [
        "page",
        "popup"
      ]
    }
  },
  {
    "name": "Popover",
    "source": "components/primitives/popover.tsx",
    "family": "B32",
    "exported": true,
    "axes": {}
  },
  {
    "name": "PopoverContent",
    "source": "components/primitives/popover.tsx",
    "family": "B32",
    "exported": true,
    "axes": {
      "side": [
        "bottom",
        "inline-end",
        "inline-start",
        "left",
        "right",
        "top"
      ],
      "align": [
        "center",
        "end",
        "start"
      ]
    }
  },
  {
    "name": "PopoverDescription",
    "source": "components/primitives/popover.tsx",
    "family": "B32",
    "exported": true,
    "axes": {}
  },
  {
    "name": "PopoverHeader",
    "source": "components/primitives/popover.tsx",
    "family": "B32",
    "exported": true,
    "axes": {}
  },
  {
    "name": "PopoverTitle",
    "source": "components/primitives/popover.tsx",
    "family": "B32",
    "exported": true,
    "axes": {}
  },
  {
    "name": "PopoverTrigger",
    "source": "components/primitives/popover.tsx",
    "family": "B32",
    "exported": true,
    "axes": {}
  },
  {
    "name": "PopupEntries",
    "source": "entrypoints/popup/popup-entries.view.tsx",
    "family": "S01",
    "exported": true,
    "axes": {}
  },
  {
    "name": "PopupSettings",
    "source": "entrypoints/popup/popup-settings.view.tsx",
    "family": "S01",
    "exported": true,
    "axes": {}
  },
  {
    "name": "PopupSync",
    "source": "entrypoints/popup/popup-sync.view.tsx",
    "family": "S01",
    "exported": true,
    "axes": {}
  },
  {
    "name": "PopupVaultAccess",
    "source": "entrypoints/popup/popup-vault-access.view.tsx",
    "family": "S01",
    "exported": true,
    "axes": {}
  },
  {
    "name": "PopupView",
    "source": "entrypoints/popup/popup.view.tsx",
    "family": "S01",
    "exported": true,
    "axes": {}
  },
  {
    "name": "PopupWorkspace",
    "source": "entrypoints/popup/popup-workspace.view.tsx",
    "family": "S01",
    "exported": true,
    "axes": {}
  },
  {
    "name": "Progress",
    "source": "components/primitives/progress.tsx",
    "family": "B34",
    "exported": true,
    "axes": {}
  },
  {
    "name": "ProgressIndicator",
    "source": "components/primitives/progress.tsx",
    "family": "B34",
    "exported": true,
    "axes": {}
  },
  {
    "name": "ProgressLabel",
    "source": "components/primitives/progress.tsx",
    "family": "B34",
    "exported": true,
    "axes": {}
  },
  {
    "name": "ProgressTrack",
    "source": "components/primitives/progress.tsx",
    "family": "B34",
    "exported": true,
    "axes": {}
  },
  {
    "name": "ProgressValue",
    "source": "components/primitives/progress.tsx",
    "family": "B34",
    "exported": true,
    "axes": {}
  },
  {
    "name": "RadioGroup",
    "source": "components/primitives/radio-group.tsx",
    "family": "B08",
    "exported": true,
    "axes": {}
  },
  {
    "name": "RadioGroupItem",
    "source": "components/primitives/radio-group.tsx",
    "family": "B08",
    "exported": true,
    "axes": {}
  },
  {
    "name": "RecoverVaultAccess",
    "source": "features/vault-setup/recover-vault-access.view.tsx",
    "family": "S02",
    "exported": true,
    "axes": {}
  },
  {
    "name": "RecoveryExportChoices",
    "source": "features/recovery/recovery.view.tsx",
    "family": "P17",
    "exported": true,
    "axes": {}
  },
  {
    "name": "RecoveryGuide",
    "source": "features/recovery/recovery.view.tsx",
    "family": "P17",
    "exported": true,
    "axes": {}
  },
  {
    "name": "RecoveryPhraseGrid",
    "source": "features/recovery/recovery.view.tsx",
    "family": "P16",
    "exported": true,
    "axes": {}
  },
  {
    "name": "RecoveryVerification",
    "source": "features/recovery/recovery.view.tsx",
    "family": "P19",
    "exported": true,
    "axes": {}
  },
  {
    "name": "RecoveryWordInput",
    "source": "features/recovery/recovery.view.tsx",
    "family": "P18",
    "exported": true,
    "axes": {}
  },
  {
    "name": "ResizableHandle",
    "source": "components/primitives/resizable.tsx",
    "family": "B36",
    "exported": true,
    "axes": {}
  },
  {
    "name": "ResizablePanel",
    "source": "components/primitives/resizable.tsx",
    "family": "B36",
    "exported": true,
    "axes": {}
  },
  {
    "name": "ResizablePanelGroup",
    "source": "components/primitives/resizable.tsx",
    "family": "B36",
    "exported": true,
    "axes": {
      "orientation": [
        "horizontal",
        "vertical"
      ]
    }
  },
  {
    "name": "ResolutionSelector",
    "source": "features/sync/sync-review.view.tsx",
    "family": "P22",
    "exported": true,
    "axes": {}
  },
  {
    "name": "ReviewSummary",
    "source": "features/sync/sync-review.view.tsx",
    "family": "P22",
    "exported": true,
    "axes": {}
  },
  {
    "name": "S3SetupGuide",
    "source": "features/sync/s3-setup-guide.view.tsx",
    "family": "S04",
    "exported": true,
    "axes": {}
  },
  {
    "name": "SafetyHelp",
    "source": "components/layout/sections.view.tsx",
    "family": "P04",
    "exported": true,
    "axes": {}
  },
  {
    "name": "SearchField",
    "source": "features/entries/search-field.view.tsx",
    "family": "P10",
    "exported": true,
    "axes": {
      "presentation": [
        "default",
        "popup"
      ]
    }
  },
  {
    "name": "SecretField",
    "source": "components/feedback/action-feedback.view.tsx",
    "family": "P13",
    "exported": true,
    "axes": {}
  },
  {
    "name": "SelectionCheckbox",
    "source": "features/entries/entry-table.view.tsx",
    "family": "P11",
    "exported": false,
    "axes": {}
  },
  {
    "name": "Separator",
    "source": "components/primitives/separator.tsx",
    "family": "B18",
    "exported": true,
    "axes": {
      "orientation": [
        "horizontal",
        "vertical"
      ]
    }
  },
  {
    "name": "SettingsSection",
    "source": "components/layout/sections.view.tsx",
    "family": "P03",
    "exported": true,
    "axes": {}
  },
  {
    "name": "SetupChecklist",
    "source": "features/sync/setup-checklist.view.tsx",
    "family": "S04",
    "exported": true,
    "axes": {}
  },
  {
    "name": "SetupConnection",
    "source": "features/vault-setup/setup-connection.view.tsx",
    "family": "S02",
    "exported": true,
    "axes": {}
  },
  {
    "name": "SetupCopy",
    "source": "features/sync/s3-setup-guide.view.tsx",
    "family": "S04",
    "exported": false,
    "axes": {}
  },
  {
    "name": "SetupDevice",
    "source": "features/vault-setup/setup-device.view.tsx",
    "family": "S02",
    "exported": true,
    "axes": {}
  },
  {
    "name": "SetupLayout",
    "source": "components/layout/sections.view.tsx",
    "family": "P02",
    "exported": true,
    "axes": {}
  },
  {
    "name": "SetupLink",
    "source": "features/sync/s3-setup-guide.view.tsx",
    "family": "S04",
    "exported": false,
    "axes": {}
  },
  {
    "name": "SetupLocation",
    "source": "features/sync/s3-setup-guide.view.tsx",
    "family": "S04",
    "exported": false,
    "axes": {}
  },
  {
    "name": "SetupOrganization",
    "source": "features/vault-setup/setup-organization.view.tsx",
    "family": "S02",
    "exported": true,
    "axes": {}
  },
  {
    "name": "SetupPassword",
    "source": "features/vault-setup/setup-password.view.tsx",
    "family": "S02",
    "exported": true,
    "axes": {}
  },
  {
    "name": "SetupRecoveryView",
    "source": "features/vault-setup/setup-recovery.view.tsx",
    "family": "S02",
    "exported": true,
    "axes": {}
  },
  {
    "name": "SetupStage",
    "source": "features/sync/setup-checklist.view.tsx",
    "family": "S04",
    "exported": true,
    "axes": {}
  },
  {
    "name": "SetupStep",
    "source": "features/sync/s3-setup-guide.view.tsx",
    "family": "S04",
    "exported": false,
    "axes": {}
  },
  {
    "name": "SetupVaultAccess",
    "source": "features/vault-setup/setup-vault-access.view.tsx",
    "family": "S02",
    "exported": true,
    "axes": {}
  },
  {
    "name": "SetupWelcome",
    "source": "features/vault-setup/setup-welcome.view.tsx",
    "family": "S02",
    "exported": true,
    "axes": {}
  },
  {
    "name": "Sheet",
    "source": "components/primitives/sheet.tsx",
    "family": "B28",
    "exported": true,
    "axes": {}
  },
  {
    "name": "SheetClose",
    "source": "components/primitives/sheet.tsx",
    "family": "B28",
    "exported": true,
    "axes": {}
  },
  {
    "name": "SheetContent",
    "source": "components/primitives/sheet.tsx",
    "family": "B28",
    "exported": true,
    "axes": {
      "side": [
        "bottom",
        "left",
        "right",
        "top"
      ]
    }
  },
  {
    "name": "SheetDescription",
    "source": "components/primitives/sheet.tsx",
    "family": "B28",
    "exported": true,
    "axes": {}
  },
  {
    "name": "SheetFooter",
    "source": "components/primitives/sheet.tsx",
    "family": "B28",
    "exported": true,
    "axes": {}
  },
  {
    "name": "SheetHeader",
    "source": "components/primitives/sheet.tsx",
    "family": "B28",
    "exported": true,
    "axes": {}
  },
  {
    "name": "SheetOverlay",
    "source": "components/primitives/sheet.tsx",
    "family": "B28",
    "exported": false,
    "axes": {}
  },
  {
    "name": "SheetPortal",
    "source": "components/primitives/sheet.tsx",
    "family": "B28",
    "exported": false,
    "axes": {}
  },
  {
    "name": "SheetTitle",
    "source": "components/primitives/sheet.tsx",
    "family": "B28",
    "exported": true,
    "axes": {}
  },
  {
    "name": "SheetTrigger",
    "source": "components/primitives/sheet.tsx",
    "family": "B28",
    "exported": true,
    "axes": {}
  },
  {
    "name": "Sidebar",
    "source": "components/primitives/sidebar.tsx",
    "family": "B27",
    "exported": true,
    "axes": {
      "variant": [
        "floating",
        "inset",
        "sidebar"
      ],
      "side": [
        "left",
        "right"
      ],
      "collapsible": [
        "icon",
        "none",
        "offcanvas"
      ]
    }
  },
  {
    "name": "SidebarContent",
    "source": "components/primitives/sidebar.tsx",
    "family": "B27",
    "exported": true,
    "axes": {}
  },
  {
    "name": "SidebarFooter",
    "source": "components/primitives/sidebar.tsx",
    "family": "B27",
    "exported": true,
    "axes": {}
  },
  {
    "name": "SidebarGroup",
    "source": "components/primitives/sidebar.tsx",
    "family": "B27",
    "exported": true,
    "axes": {}
  },
  {
    "name": "SidebarGroupAction",
    "source": "components/primitives/sidebar.tsx",
    "family": "B27",
    "exported": true,
    "axes": {}
  },
  {
    "name": "SidebarGroupContent",
    "source": "components/primitives/sidebar.tsx",
    "family": "B27",
    "exported": true,
    "axes": {}
  },
  {
    "name": "SidebarGroupLabel",
    "source": "components/primitives/sidebar.tsx",
    "family": "B27",
    "exported": true,
    "axes": {}
  },
  {
    "name": "SidebarHeader",
    "source": "components/primitives/sidebar.tsx",
    "family": "B27",
    "exported": true,
    "axes": {}
  },
  {
    "name": "SidebarInput",
    "source": "components/primitives/sidebar.tsx",
    "family": "B27",
    "exported": true,
    "axes": {}
  },
  {
    "name": "SidebarInset",
    "source": "components/primitives/sidebar.tsx",
    "family": "B27",
    "exported": true,
    "axes": {}
  },
  {
    "name": "SidebarMenu",
    "source": "components/primitives/sidebar.tsx",
    "family": "B27",
    "exported": true,
    "axes": {}
  },
  {
    "name": "SidebarMenuAction",
    "source": "components/primitives/sidebar.tsx",
    "family": "B27",
    "exported": true,
    "axes": {}
  },
  {
    "name": "SidebarMenuBadge",
    "source": "components/primitives/sidebar.tsx",
    "family": "B27",
    "exported": true,
    "axes": {}
  },
  {
    "name": "SidebarMenuButton",
    "source": "components/primitives/sidebar.tsx",
    "family": "B27",
    "exported": true,
    "axes": {
      "variant": [
        "default",
        "outline"
      ],
      "size": [
        "default",
        "lg",
        "sm"
      ]
    }
  },
  {
    "name": "SidebarMenuItem",
    "source": "components/primitives/sidebar.tsx",
    "family": "B27",
    "exported": true,
    "axes": {}
  },
  {
    "name": "SidebarMenuSkeleton",
    "source": "components/primitives/sidebar.tsx",
    "family": "B27",
    "exported": true,
    "axes": {}
  },
  {
    "name": "SidebarMenuSub",
    "source": "components/primitives/sidebar.tsx",
    "family": "B27",
    "exported": true,
    "axes": {}
  },
  {
    "name": "SidebarMenuSubButton",
    "source": "components/primitives/sidebar.tsx",
    "family": "B27",
    "exported": true,
    "axes": {
      "size": [
        "md",
        "sm"
      ]
    }
  },
  {
    "name": "SidebarMenuSubItem",
    "source": "components/primitives/sidebar.tsx",
    "family": "B27",
    "exported": true,
    "axes": {}
  },
  {
    "name": "SidebarProvider",
    "source": "components/primitives/sidebar.tsx",
    "family": "B27",
    "exported": true,
    "axes": {}
  },
  {
    "name": "SidebarRail",
    "source": "components/primitives/sidebar.tsx",
    "family": "B27",
    "exported": true,
    "axes": {}
  },
  {
    "name": "SidebarSeparator",
    "source": "components/primitives/sidebar.tsx",
    "family": "B27",
    "exported": true,
    "axes": {
      "orientation": [
        "horizontal",
        "vertical"
      ]
    }
  },
  {
    "name": "SidebarTrigger",
    "source": "components/primitives/sidebar.tsx",
    "family": "B27",
    "exported": true,
    "axes": {
      "variant": [
        "default",
        "destructive",
        "ghost",
        "link",
        "outline",
        "secondary"
      ],
      "size": [
        "default",
        "icon",
        "icon-lg",
        "icon-sm",
        "icon-xs",
        "lg",
        "sm",
        "xs"
      ]
    }
  },
  {
    "name": "SiteIcon",
    "source": "features/entries/site-icon.view.tsx",
    "family": "P11",
    "exported": true,
    "axes": {}
  },
  {
    "name": "SiteIconSettings",
    "source": "features/site-icons/site-icon-settings.view.tsx",
    "family": "P11",
    "exported": true,
    "axes": {}
  },
  {
    "name": "SiteIconsProvider",
    "source": "features/site-icons/site-icons-provider.view.tsx",
    "family": "P11",
    "exported": true,
    "axes": {}
  },
  {
    "name": "Skeleton",
    "source": "components/primitives/skeleton.tsx",
    "family": "B13",
    "exported": true,
    "axes": {}
  },
  {
    "name": "Slider",
    "source": "components/primitives/slider.tsx",
    "family": "B09",
    "exported": true,
    "axes": {
      "orientation": [
        "horizontal",
        "vertical"
      ]
    }
  },
  {
    "name": "Spinner",
    "source": "components/primitives/spinner.tsx",
    "family": "B12",
    "exported": true,
    "axes": {}
  },
  {
    "name": "StepNavigation",
    "source": "components/layout/sections.view.tsx",
    "family": "P01",
    "exported": true,
    "axes": {}
  },
  {
    "name": "Switch",
    "source": "components/primitives/switch.tsx",
    "family": "B31",
    "exported": true,
    "axes": {
      "size": [
        "default",
        "sm"
      ]
    }
  },
  {
    "name": "SyncAccessKeys",
    "source": "features/sync/sync-access-keys.view.tsx",
    "family": "S03",
    "exported": true,
    "axes": {}
  },
  {
    "name": "SyncManagement",
    "source": "features/sync/sync-management.view.tsx",
    "family": "S03",
    "exported": true,
    "axes": {}
  },
  {
    "name": "SyncPage",
    "source": "features/sync/sync-page.view.tsx",
    "family": "S03",
    "exported": true,
    "axes": {}
  },
  {
    "name": "SyncReview",
    "source": "features/sync/sync-review.view.tsx",
    "family": "P22",
    "exported": true,
    "axes": {}
  },
  {
    "name": "SyncStatus",
    "source": "features/sync/sync-review.view.tsx",
    "family": "P21",
    "exported": true,
    "axes": {}
  },
  {
    "name": "SyncTrustReview",
    "source": "features/sync/sync-trust-review.view.tsx",
    "family": "S03",
    "exported": true,
    "axes": {}
  },
  {
    "name": "Table",
    "source": "components/primitives/table.tsx",
    "family": "B29",
    "exported": true,
    "axes": {}
  },
  {
    "name": "TableBody",
    "source": "components/primitives/table.tsx",
    "family": "B29",
    "exported": true,
    "axes": {}
  },
  {
    "name": "TableCaption",
    "source": "components/primitives/table.tsx",
    "family": "B29",
    "exported": true,
    "axes": {}
  },
  {
    "name": "TableCell",
    "source": "components/primitives/table.tsx",
    "family": "B29",
    "exported": true,
    "axes": {}
  },
  {
    "name": "TableFooter",
    "source": "components/primitives/table.tsx",
    "family": "B29",
    "exported": true,
    "axes": {}
  },
  {
    "name": "TableHead",
    "source": "components/primitives/table.tsx",
    "family": "B29",
    "exported": true,
    "axes": {}
  },
  {
    "name": "TableHeader",
    "source": "components/primitives/table.tsx",
    "family": "B29",
    "exported": true,
    "axes": {}
  },
  {
    "name": "TableRow",
    "source": "components/primitives/table.tsx",
    "family": "B29",
    "exported": true,
    "axes": {}
  },
  {
    "name": "Tabs",
    "source": "components/primitives/tabs.tsx",
    "family": "B20",
    "exported": true,
    "axes": {
      "orientation": [
        "horizontal",
        "vertical"
      ]
    }
  },
  {
    "name": "TabsContent",
    "source": "components/primitives/tabs.tsx",
    "family": "B20",
    "exported": true,
    "axes": {}
  },
  {
    "name": "TabsList",
    "source": "components/primitives/tabs.tsx",
    "family": "B20",
    "exported": true,
    "axes": {
      "variant": [
        "default",
        "line"
      ]
    }
  },
  {
    "name": "TabsTrigger",
    "source": "components/primitives/tabs.tsx",
    "family": "B20",
    "exported": true,
    "axes": {}
  },
  {
    "name": "TagEditor",
    "source": "features/tags/tag-management.view.tsx",
    "family": "S05",
    "exported": false,
    "axes": {}
  },
  {
    "name": "TagGroupHeading",
    "source": "features/tags/tag-visuals.view.tsx",
    "family": "P30",
    "exported": true,
    "axes": {}
  },
  {
    "name": "TagManagementView",
    "source": "features/tags/tag-management.view.tsx",
    "family": "S05",
    "exported": true,
    "axes": {}
  },
  {
    "name": "TagMarker",
    "source": "features/tags/tag-visuals.view.tsx",
    "family": "P30",
    "exported": true,
    "axes": {}
  },
  {
    "name": "TagPill",
    "source": "features/tags/tag-visuals.view.tsx",
    "family": "P30",
    "exported": true,
    "axes": {
      "size": [
        "default",
        "sm"
      ]
    }
  },
  {
    "name": "TagSelection",
    "source": "features/entries/tag-selection.view.tsx",
    "family": "P27",
    "exported": true,
    "axes": {}
  },
  {
    "name": "TagVisualPicker",
    "source": "features/tags/tag-visuals.view.tsx",
    "family": "P30",
    "exported": true,
    "axes": {}
  },
  {
    "name": "Textarea",
    "source": "components/primitives/textarea.tsx",
    "family": "B05",
    "exported": true,
    "axes": {}
  },
  {
    "name": "TextField",
    "source": "components/forms/fields.view.tsx",
    "family": "B03",
    "exported": true,
    "axes": {}
  },
  {
    "name": "ThemeProvider",
    "source": "features/theme/theme.context.tsx",
    "family": "P08",
    "exported": true,
    "axes": {}
  },
  {
    "name": "ThemeToggle",
    "source": "features/theme/theme-toggle.view.tsx",
    "family": "P08",
    "exported": true,
    "axes": {}
  },
  {
    "name": "Toast",
    "source": "components/primitives/toast.tsx",
    "family": "B33",
    "exported": true,
    "axes": {}
  },
  {
    "name": "ToastAction",
    "source": "components/primitives/toast.tsx",
    "family": "B33",
    "exported": true,
    "axes": {}
  },
  {
    "name": "ToastClose",
    "source": "components/primitives/toast.tsx",
    "family": "B33",
    "exported": true,
    "axes": {}
  },
  {
    "name": "ToastContent",
    "source": "components/primitives/toast.tsx",
    "family": "B33",
    "exported": true,
    "axes": {}
  },
  {
    "name": "ToastDescription",
    "source": "components/primitives/toast.tsx",
    "family": "B33",
    "exported": true,
    "axes": {}
  },
  {
    "name": "Toaster",
    "source": "components/primitives/toast.tsx",
    "family": "B33",
    "exported": true,
    "axes": {}
  },
  {
    "name": "ToastIcon",
    "source": "components/primitives/toast.tsx",
    "family": "B33",
    "exported": false,
    "axes": {}
  },
  {
    "name": "ToastList",
    "source": "components/primitives/toast.tsx",
    "family": "B33",
    "exported": false,
    "axes": {}
  },
  {
    "name": "ToastPortal",
    "source": "components/primitives/toast.tsx",
    "family": "B33",
    "exported": true,
    "axes": {}
  },
  {
    "name": "ToastProvider",
    "source": "components/primitives/toast.tsx",
    "family": "B33",
    "exported": true,
    "axes": {}
  },
  {
    "name": "ToastTitle",
    "source": "components/primitives/toast.tsx",
    "family": "B33",
    "exported": true,
    "axes": {}
  },
  {
    "name": "ToastViewport",
    "source": "components/primitives/toast.tsx",
    "family": "B33",
    "exported": true,
    "axes": {}
  },
  {
    "name": "Toggle",
    "source": "components/primitives/toggle.tsx",
    "family": "B35",
    "exported": true,
    "axes": {
      "variant": [
        "default",
        "outline"
      ],
      "size": [
        "default",
        "lg",
        "sm"
      ]
    }
  },
  {
    "name": "ToggleGroup",
    "source": "components/primitives/toggle-group.tsx",
    "family": "B35",
    "exported": true,
    "axes": {
      "variant": [
        "default",
        "outline"
      ],
      "size": [
        "default",
        "lg",
        "sm"
      ],
      "orientation": [
        "horizontal",
        "vertical"
      ]
    }
  },
  {
    "name": "ToggleGroupItem",
    "source": "components/primitives/toggle-group.tsx",
    "family": "B35",
    "exported": true,
    "axes": {
      "variant": [
        "default",
        "outline"
      ],
      "size": [
        "default",
        "lg",
        "sm"
      ]
    }
  },
  {
    "name": "Tooltip",
    "source": "components/primitives/tooltip.tsx",
    "family": "B15",
    "exported": true,
    "axes": {}
  },
  {
    "name": "TooltipContent",
    "source": "components/primitives/tooltip.tsx",
    "family": "B15",
    "exported": true,
    "axes": {
      "side": [
        "bottom",
        "inline-end",
        "inline-start",
        "left",
        "right",
        "top"
      ],
      "align": [
        "center",
        "end",
        "start"
      ]
    }
  },
  {
    "name": "TooltipProvider",
    "source": "components/primitives/tooltip.tsx",
    "family": "B15",
    "exported": true,
    "axes": {}
  },
  {
    "name": "TooltipTrigger",
    "source": "components/primitives/tooltip.tsx",
    "family": "B15",
    "exported": true,
    "axes": {}
  },
  {
    "name": "TransferInput",
    "source": "features/devices/devices.view.tsx",
    "family": "P24",
    "exported": true,
    "axes": {}
  },
  {
    "name": "TransferOutput",
    "source": "features/devices/devices.view.tsx",
    "family": "P24",
    "exported": true,
    "axes": {}
  },
  {
    "name": "UnlockForm",
    "source": "features/vault-access/access-forms.view.tsx",
    "family": "F01",
    "exported": true,
    "axes": {}
  },
  {
    "name": "UsernameControls",
    "source": "features/password-tools/generator.view.tsx",
    "family": "P20",
    "exported": true,
    "axes": {}
  },
  {
    "name": "VaultApplication",
    "source": "entrypoints/options/vault-application.view.tsx",
    "family": "S02",
    "exported": true,
    "axes": {}
  },
  {
    "name": "VaultLockSettings",
    "source": "features/settings/vault-lock-settings.view.tsx",
    "family": "S02",
    "exported": true,
    "axes": {}
  },
  {
    "name": "VaultPicker",
    "source": "features/vault-access/vault-picker.view.tsx",
    "family": "P09",
    "exported": true,
    "axes": {}
  },
  {
    "name": "VaultSettingsView",
    "source": "features/settings/vault-settings.view.tsx",
    "family": "S02",
    "exported": true,
    "axes": {}
  },
  {
    "name": "VaultToolbar",
    "source": "entrypoints/components/app-navigation.view.tsx",
    "family": "P28",
    "exported": true,
    "axes": {}
  }
] as const;
