import type { catalog } from "./catalog";
export type CatalogId = (typeof catalog)[number]["id"];
// Gallery guidance is review material; it is never imported by product views.
export const usage = {
  S01: "Compact popup without heading subtitles or taglines, with a working handoff to Options in the extension. Review no-vault, existing-vault, loading, storage-error and opening-error states.",
  S02: "Password-pending and password-unavailable scenarios exercise the assessment after typing; retry in the unavailable scenario succeeds. Options setup without heading subtitles: two selectable create/connect cards with radio indicators, requirements for each path, one Continue action and single-column forms, password and device steps, connection sequence, and appearance. Password setup includes match feedback, strength feedback after typing, retryable assessment errors and Back/Continue navigation.",
  B01: "Use for an action such as saving an entry. Give the main action the strongest emphasis; keep supporting actions quieter.",
  B02: "Groups a field's label, input, help and error so they remain connected. Use it whenever someone must enter or choose a value.",
  B03: "Use for a short, single-line value such as a device name or login. Password entry uses the dedicated PasswordField example.",
  B04: "Keeps an input and its related controls together, such as a password with Show or a search box with Clear.",
  B05: "Use for text that needs several lines, such as a pasted recovery phrase or enrollment artifact. It does not parse or verify that text.",
  B06: "Use for a short list of fixed choices, such as lock duration. The browser supplies the selection menu. For a searchable list, see Combobox.",
  B07: "Use for independent choices or an explicit acknowledgment. Several checkboxes can be selected together, as in generator character settings.",
  B08: "Use when exactly one of a few visible choices applies, such as keeping the local or remote version during sync review.",
  B09: "Use for quick adjustment within a range, such as generated-password length. Keep a numeric input beside it for precise entry.",
  B10: "Keeps an important explanation or outcome visible beside the affected content. Use it for recovery guidance and errors that need attention.",
  B11: "Adds a short label to an item, such as a tag or sync state. Its text must explain the meaning without relying on color alone.",
  B12: "Shows that an action is still running when its progress is unknown. Pair it with text such as Checking access so the wait has a meaning.",
  B13: "Reserves the approximate shape of content while it loads, such as entry rows. Use an empty state once loading finishes with no results.",
  B14: "Lets readers expand optional detail without leaving the page. Put recovery essentials in visible text and use this for longer explanations.",
  B15: "Adds a short hint on hover or keyboard focus. A button still needs its own accessible name; essential instructions belong in visible text.",
  B16: "Collects secondary actions for one item, such as editing or reviewing removal of an entry. Keep the most frequent action directly available.",
  B17: "Interrupts an action for a consequential decision, such as removing a local vault. Name what will change, explain the consequence and start focus on Cancel.",
  B18: "Visually separates related groups, such as account details and actions. Use spacing and headings to carry the structure as well.",
  B19: "Opens a focused, temporary task over the current page. Suitable for a small editor; first-vault setup belongs on the full options page.",
  B20: "Switches between related panels in the same context, such as password and username generators. Application destinations use navigation instead.",
  B21: "Gives a useful next action when a region has no content, such as adding the first entry or clearing a search that found nothing.",
  B22: "Presents one object in a list with its description and actions. Use for entries, devices or export methods that people need to scan quickly.",
  B23: "Groups content that people should understand as one unit, such as a settings category. Use simple headings and spacing when a container adds no meaning.",
  B24: "Combines typing and selection for longer lists. Use it to find a vault or choose existing tags; it does not imply that typing creates a new item.",
  B25: "Keeps closely related actions together, such as Generate and its settings menu. A selected mode needs selection semantics, as in Toggle Group.",
  B26: "Shows a file's name, type, status and available actions. Useful for recovery downloads or enrollment artifacts; displaying a file does not verify its contents.",
  B27: "Provides persistent navigation on a wide options page and a menu at narrow widths. The gallery's left-hand navigation is a working example.",
  B28: "Slides in secondary details while preserving the current page context, such as selected-file information. Long setup forms need the options page's full space.",
  B29: "Aligns repeated fields in rows and columns so entries can be compared. The interactive example adds search, tags, sorting, selection and pagination through the entries feature.",
  B30: "Moves through a list in predictable pages. Show the current page, result count and disabled boundary actions so people know where they are.",
  B31: "Use for a preference that takes effect immediately when switched, such as a display option. Use a checkbox when the choice is part of a form saved later.",
  B32: "Anchors a small, temporary panel to its trigger, such as display preferences. A larger editing task needs a Dialog or a full page.",
  B33: "Briefly confirms a completed action, such as saving a preference. Keep actionable failures beside the affected form so they do not disappear.",
  B34: "Communicates how an operation is progressing. Show a percentage only when the caller knows the total; otherwise use the indeterminate state.",
  B35: "Switches a compact presentation preference, such as list or table view. Use Tabs when the choices identify distinct content panels.",
  B36: "Lets people drag a divider to allocate space between panels. An optional options-page use is an entry list beside its details. It is a layout control, with no role in password fields or first-vault setup.",
  B37: "Displays a keyboard key or shortcut, such as Esc for dismissing a dialog. It only explains an existing shortcut and does not register one.",
  B38: "Provides a compact visual identifier for a vault or device. This library uses local initials; the example does not fetch website icons or profile images.",
  P01: "Review current, completed, upcoming and error states with the state selector. Shows progress through setup and lets people return to steps that the flow allows. The flow owner decides which steps are reachable.",
  P02: "Arranges a setup step's heading, form, help and actions on the options page. Use the Setup help chooser to review the two-column layout with help or the full-width layout without it. The setup feature supplies content and progression.",
  P03: "Groups one editable settings topic with its explanation and actions. Use separate sections for device preferences and consequential actions such as local removal.",
  P04: "Explains a sensitive action at the point of use. Keep essential guidance visible and offer expandable answers for readers who want more detail.",
  P05: "Shows a Caps Lock notice when the focused input detects it; keyboard input and blur review that state. Accepts a password with an explicit Show/Hide control. Use for master, entry and credential secrets; masking changes visibility, not whether the input value exists in memory.",
  P06: "Displays the strength assessment supplied by the application. The empty state renders nothing. Feedback appears after password input and uses named ratings, pending and unavailable states.",
  P07: "Chooses how long this device's vault session stays unlocked. The application supplies allowed durations and their timing meaning; other devices keep their own settings.",
  P08: "Chooses light, dark or system appearance. The specimen changes its selected preference; the gallery's top-bar Theme control changes the review page.",
  P09: "Finds and selects a local vault before unlocking or recovering it. The options-page composition supplies the list and handles creation of another vault.",
  P10: "Searches entry metadata while keeping clearing and result feedback close to the input. Search targets logins, websites and tags, not stored passwords.",
  P11: "EntryRow shows one login; EntryList supports scanning; EntrySelection adds a choice action. EntryTable adds comparison, filtering and paging for a larger vault. Selection persists across pages and clears when filters change; review those transitions here. These remain entries-feature widgets.",
  P12: "Presents one read-only field, such as a login or website. Supported web links open separately; unsupported links remain plain text.",
  P13: "Displays a stored secret only after an explicit reveal. The caller retrieves and discards the value, and can provide a copy action without showing it first.",
  P14: "Presents a copy action and its pending, success or error outcome. The caller owns clipboard access and clearing.",
  P15: "Explains why an entry region is empty and offers the appropriate next step. A new vault needs Add entry; a search with no results needs Clear filters.",
  P16: "Shows numbered recovery words when the person is ready to save them privately. Concealed words are omitted from the rendered display.",
  P17: "Offers recovery-record formats with guidance for each method. RecoveryGuide previews the ordered words for a saved or printed record.",
  P18: "Numbered editing takes explicit word slots so blank positions remain stable. Whole-phrase text is split on whitespace runs when choosing numbered mode. Both modes expose errors and disabled states. Accepts a complete recovery phrase as pasted text or numbered words. Preserve order; the recovery workflow performs validation using the required local vault data.",
  P19: "Checks three positions against the person's saved recovery record. Production supplies three randomly chosen positions; this example keeps fixed positions so retry behavior can be reviewed.",
  P20: "Adjusts password or username generation settings, then lets someone review and use the result. Core supplies randomness and validation.",
  P21: "Explains sync status and exposes only the actions currently available. Pending local changes remain distinguishable from a completed upload.",
  P22: "Shows local and remote differences, collects permitted resolutions and summarizes the choices before applying them. Password differences are indicators; the widget does not reveal values or invent merge rules.",
  P23: "Identifies a device and its current access state. For another device, it can offer a revocation review that explains what revocation can and cannot change.",
  P24: "Receives an enrollment artifact by text or file selection and presents outgoing-artifact actions. The workflow owns parsing and trust verification.",
  P25: "Confirms a specific consequential action with its affected vault, entry or device and supplied consequences. An optional acknowledgment gates confirmation; pending work cannot be dismissed as though it were cancelled.",
  P26: "Keeps a supplied action outcome beside the relevant content. Use persistent, retryable feedback for failures that require a decision or correction.",
  P27: "Selects existing tags by readable names and allows removal from the selection. The entries feature receives their IDs; this control does not create or rename tags.",
  P28: "AppNavigation changes allowed destinations; VaultToolbar exposes the current vault and quick actions such as Lock and Open options. The popup/options shell connects their callbacks.",
  F01: "Unlocks a selected local vault using its master password and a device-local lock duration.",
  F02: "Adds or edits a login, website, password and existing tags. In edit mode the existing password stays concealed; the owner must define how a blank replacement is handled.",
  F03: "The strength selector exposes ready, pending, unavailable and retry behavior in the form. Chooses and confirms the master password during first-vault setup on the options page. Independent reveal controls help catch typing mistakes before continuing.",
  F04: "Changes the unlock password for this device's local vault. It asks for the current password and a confirmed replacement; the owner clears all values after success.",
  F05: "Configures the person's S3 bucket and credentials. Test access and Save configuration are distinct actions; testing must not silently enable sync or upload data.",
  F06: "Recovers access to an existing local vault using recovery words and a new password. Missing required local data blocks submission; the successful workflow must provide replacement recovery words.",
  F07: "Sets this device's editable name and local lock duration during setup or later settings. Changes apply to this device, with the application owning persistence.",
} satisfies Record<CatalogId, string>;
